/* Math Live TV V5.8.3 · © 2026 Rene M. Velazquez Avila · Todos los derechos reservados. */
const $=s=>document.querySelector(s);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const effectiveUnanswered=p=>Math.max(0,Number(game?.count||15)-Number(p.answered||0));
const face=id=>`<img src="assets/${/^avatar-\d{2}$/.test(id||'')?id:'avatar-01'}.webp?v=583" alt="">`;
const params=new URLSearchParams(location.search), code=params.get('code')||'';
let db=null,auth=null,game=null,players=[],timer=null,knownIds=new Set(),audioCtx=null,lastStatus=null,playersSnapshotReady=false;
function tone(freq=740,dur=.10,gain=.035){try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(gain,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur)}catch(e){}}
function joinSound(){tone(784,.09);setTimeout(()=>tone(988,.11),80)}function startSound(){tone(523,.07);setTimeout(()=>tone(659,.07),75);setTimeout(()=>tone(784,.12),150)}function endSound(){tone(659,.09);setTimeout(()=>tone(784,.13),90)}
function showOnly(id){['lobby','playing','final','tvError'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id))}
function fail(msg){showOnly('tvError');$('#tvError').textContent=msg;stopTimer()}
function fmt(sec){sec=Math.max(0,Math.ceil(sec));return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function millis(t){return t&&typeof t.toMillis==='function'?t.toMillis():null}
function remaining(){const st=millis(game?.startedAt);if(!st)return Number(game?.durationSeconds||900);return Math.max(0,Number(game?.durationSeconds||900)-(Date.now()-st)/1000)}
function stopTimer(){if(timer){clearInterval(timer);timer=null}}
function startTimer(){stopTimer();const tick=()=>{$('#tvTimer').textContent=fmt(remaining());if(remaining()<=0)stopTimer()};tick();timer=setInterval(tick,500)}
function mode(){return window.MathLiveModes?.get(game?.gameType||'integrated')||{id:'integrated',icon:'🌟',name:'Integrado',tv:'progress-track',rankingLive:false}}
function lobbyCard(p,i){return `<div class="card"><span class="entryNo">${i+1}</span><div class="face">${face(p.avatar)}</div><div class="name">${esc(p.name)}</div><div class="state">Entrada ${i+1} · Conectado ✓</div></div>`}
function progressCard(p,rank=null){const total=Number(game?.count||15),answered=Math.min(total,Number(p.answered||0)),pct=total?Math.round(answered/total*100):0;const dots=Array.from({length:total},(_,i)=>`<span class="dot ${i<answered?'done':''}"></span>`).join('');return `<div class="card">${rank?`<span class="rank">${rank}.º</span>`:''}<div class="face">${face(p.avatar)}</div><div class="name">${esc(p.name)}</div><div class="state">${answered}/${total} respondidas</div><div class="bar"><div class="fill" style="width:${pct}%"></div></div>${rank?'':`<div class="dots" aria-label="${answered} de ${total} respondidas">${dots}</div>`}</div>`}
function liveOrder(list){return [...list].sort((a,b)=>Number(b.score||0)-Number(a.score||0)||Number(b.answered||0)-Number(a.answered||0)||String(a.name).localeCompare(String(b.name),'es'))}
function finalOrder(list){return [...list].sort((a,b)=>{const sd=Number(b.score||0)-Number(a.score||0);if(sd)return sd;const ta=millis(a.finishedAt)??Infinity,tb=millis(b.finishedAt)??Infinity;if(ta!==tb)return ta-tb;return String(a.name).localeCompare(String(b.name),'es')})}
function renderLobby(){showOnly('lobby');$('#tvTimer').textContent=fmt(Number(game?.durationSeconds||900));$('#tvCode').textContent=game?.code||code;$('#tvMeta').textContent=`${game?.gradeName||''} · ${mode().icon} ${mode().name} · ${game?.count||15} desafíos`;$('#tvCount').textContent=`${players.length} estudiante${players.length===1?'':'s'} conectado${players.length===1?'':'s'}`;$('#lobbyGrid').innerHTML=players.length?players.map((p,i)=>lobbyCard(p,i)).join(''):'<div class="empty">Esperando estudiantes…</div>'}
function modeText(m){const map={integrated:['🌟 Modo Integrado','Avanza por progreso. El ranking permanece oculto hasta el final.'],challenge:['⚡ Reto rápido · Carrera en vivo','Precisión primero. El progreso cambia las posiciones en tiempo real.'],discover:['🔎 Descubre','Cada desafío abre una nueva etapa del camino.'],memory:['🧠 Memoria','Las parejas encontradas hacen avanzar el progreso.'],crossword:['✏️ Crucigrama','Cada pista resuelta completa una parte del reto.'],build:['🧩 Construye','Cada construcción correcta hace crecer el progreso.']};return map[m.id]||map.integrated}
function renderPlaying(){showOnly('playing');const m=mode(),t=modeText(m);document.body.dataset.mode=m.id;$('#modeBanner').textContent=t[0];$('#modeHint').textContent=t[1];let list=m.rankingLive?liveOrder(players):[...players].sort((a,b)=>String(a.name).localeCompare(String(b.name),'es'));$('#playGrid').innerHTML=list.length?list.map((p,i)=>progressCard(p,m.rankingLive?i+1:null)).join(''):'<div class="empty">Partida en progreso…</div>';startTimer()}
function renderFinal(){showOnly('final');stopTimer();$('#tvTimer').textContent='00:00';const list=finalOrder(players),med=['🥇','🥈','🥉'];$('#podium').innerHTML=list.slice(0,3).map((p,i)=>`<div class="pod ${i===0?'first':i===1?'second':'third'}"><div class="medal">${med[i]}</div><div class="face">${face(p.avatar)}</div><div class="name">${esc(p.name)}</div><div class="state">⭐ ${Number(p.score||0)}/${Number(game?.count||15)}</div></div>`).join('');$('#resultGrid').innerHTML=list.map((p,i)=>`<div class="card"><span class="rank">${i+1}.º</span><div class="face">${face(p.avatar)}</div><div class="name">${esc(p.name)}</div><div class="state">⭐ ${Number(p.score||0)}/${Number(game?.count||15)} · ${effectiveUnanswered(p)} sin responder</div></div>`).join('')}
function render(){if(!game)return;const s=game.status;if(s==='lobby')renderLobby();else if(s==='playing')renderPlaying();else if(s==='finished')renderFinal();else if(s==='cancelled')fail('Esta partida fue cancelada. El maestro generará un nuevo código.')}
(async()=>{try{if(!/^\d{6}$/.test(code))return fail('Falta un código de partida válido en la dirección de la pantalla TV.');const cfg=window.MATHLIVE_FIREBASE_CONFIG||{};if(!window.firebase||!cfg.apiKey)return fail('Firebase no está configurado.');if(!firebase.apps.length)firebase.initializeApp(cfg);db=firebase.firestore();auth=firebase.auth();const user=await new Promise(resolve=>{const off=auth.onAuthStateChanged(u=>{off();resolve(u)})});if(!user||user.isAnonymous)return fail('La pantalla TV debe abrirse desde el navegador donde el maestro inició sesión.');const ref=db.collection('games').doc(code);ref.onSnapshot(s=>{if(!s.exists)return fail('No se encontró esta partida.');const next={code,...s.data()};if(lastStatus&&next.status!==lastStatus){if(next.status==='playing')startSound();if(next.status==='finished')endSound()}lastStatus=next.status;game=next;render()},e=>fail('No se pudo leer la partida. Abre la pantalla TV desde el panel del maestro.'));ref.collection('players').orderBy('joinedAt').onSnapshot(s=>{const ids=new Set(s.docs.map(d=>d.id));if(playersSnapshotReady){s.docChanges().filter(ch=>ch.type==='added'&&!knownIds.has(ch.doc.id)).forEach((_,i)=>setTimeout(joinSound,i*110))}knownIds=ids;playersSnapshotReady=true;players=s.docs.map(d=>({id:d.id,...d.data()}));render()},e=>fail('No se pudo leer la lista de estudiantes. Abre esta pantalla desde el mismo navegador del maestro.'))}catch(e){console.error(e);fail('No se pudo iniciar la pantalla TV.')}})();
