/* Math Live Student V5.8.3 · © 2026 Rene M. Velazquez Avila */
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const sections=['studentJoin','studentWait','play','finish'];
function show(id){sections.forEach(x=>$('#'+x)?.classList.toggle('hidden',x!==id));window.scrollTo({top:0,behavior:'smooth'})}
const avatars=Array.from({length:18},(_,i)=>({id:`avatar-${String(i+1).padStart(2,'0')}`,src:`assets/avatar-${String(i+1).padStart(2,'0')}.webp?v=583`}));
function avatarSrc(id){return (avatars.find(a=>a.id===id)||avatars[0]).src}
function avatarImg(id,cls='avatarImage'){return `<img class="${cls}" src="${avatarSrc(id)}" alt="Avatar" draggable="false">`}
let selectedAvatar='avatar-01',db=null,auth=null,game=null,studentId=null,questions=[],idx=0,score=0,responses=[],unsubs=[],timerHandle=null,finalizing=false;
const engine=window.MathLiveEngineV2;
function renderAvatars(){const el=$('#avatarGrid');el.innerHTML=avatars.map(a=>`<button type="button" class="avatar ${a.id===selectedAvatar?'active':''}" data-avatar="${a.id}" aria-label="Elegir avatar"><span class="avatarFace">${avatarImg(a.id)}</span></button>`).join('');$$('.avatar').forEach(b=>b.onclick=()=>{selectedAvatar=b.dataset.avatar;renderAvatars()})}
function initFirebase(){const c=window.MATHLIVE_FIREBASE_CONFIG||{};if(!window.firebase||!c.apiKey)throw Error('Firebase no está configurado.');if(!firebase.apps.length)firebase.initializeApp(c);db=firebase.firestore();auth=firebase.auth()}
async function ensureStudentAuth(){if(auth.currentUser){if(!auth.currentUser.isAnonymous)await auth.signOut();else return auth.currentUser}const c=await auth.signInAnonymously();return c.user}
function cleanup(){unsubs.forEach(f=>{try{f()}catch{}});unsubs=[];stopTimer()}
function stopTimer(){if(timerHandle){clearInterval(timerHandle);timerHandle=null}}
function fmt(sec){sec=Math.max(0,Math.ceil(sec));return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function startedMillis(){const t=game?.startedAt;return t&&typeof t.toMillis==='function'?t.toMillis():null}
function remaining(){const st=startedMillis();if(!st)return Number(game?.durationSeconds||900);return Math.max(0,Number(game?.durationSeconds||900)-(Date.now()-st)/1000)}
function runTimer(){stopTimer();const tick=async()=>{const left=remaining();$('#studentTimer').textContent=fmt(left);if(left<=0){stopTimer();await finishStudent('time')}};tick();timerHandle=setInterval(tick,500)}
function listenStudent(code){cleanup();unsubs.push(db.collection('games').doc(code).onSnapshot(s=>{if(!s.exists)return;game={code,...s.data()};if(game.status==='playing'&&$('#play').classList.contains('hidden'))startPlay();if(game.status==='finished'&&!finalizing)finishStudent(game.endedReason==='time'?'time':'teacher');if(game.status==='cancelled'){cleanup();show('studentJoin');$('#joinMsg').innerHTML='<div class="status">El maestro está modificando la partida. Espera el nuevo código.</div>'}},console.error))}
$('#joinGame').onclick=async()=>{try{let code=$('#joinCode').value.trim(),name=$('#studentName').value.trim().replace(/\s+/g,' ');if(!/^\d{6}$/.test(code)||!name){$('#joinMsg').innerHTML='<div class="status">Escribe un código válido de 6 dígitos y tu nombre.</div>';return}const user=await ensureStudentAuth(),ref=db.collection('games').doc(code),snap=await ref.get();if(!snap.exists){$('#joinMsg').innerHTML='<div class="status">Código no encontrado. Revisa los seis dígitos.</div>';return}game={code,...snap.data()};if(game.status!=='lobby'){$('#joinMsg').innerHTML='<div class="status">🔒 La partida ya comenzó. Ya no es posible unirse.</div>';return}studentId=user.uid;await ref.collection('players').doc(studentId).set({uid:user.uid,name,avatar:selectedAvatar,score:0,answered:0,finished:false,joinedAt:firebase.firestore.FieldValue.serverTimestamp()});$('#waitAvatar').innerHTML=avatarImg(selectedAvatar,'waitAvatarImg');$('#waitText').textContent=`${name}, ya estás conectado. Espera a que comience la aventura.`;localStorage.setItem('mathLiveActiveGame',JSON.stringify({code,name,avatar:selectedAvatar,uid:user.uid}));show('studentWait');listenStudent(code)}catch(e){console.error(e);$('#joinMsg').innerHTML='<div class="status">No pudimos entrar. Revisa la conexión y vuelve a intentar.</div>'}};
function startPlay(){if(!engine)return alert('No se pudo cargar el motor matemático.');const bp=Array.isArray(game?.blueprint)&&game.blueprint.length?game.blueprint:engine.createGameBlueprint(game?.grade||2,game?.count||15);questions=engine.createStudentSet(bp,studentId);idx=0;score=0;responses=[];$('#playGrade').textContent=game?.gradeName||'';show('play');renderQ();runTimer()}
function renderQ(){const q=questions[idx];$('#progress').textContent=`${idx+1} / ${questions.length}`;$('#score').textContent=score;$('#skillLabel').textContent=`${q.content} · ${q.subskill} · ${q.layer}`;$('#question').style.whiteSpace='pre-line';$('#question').textContent=q.prompt;$('#answers').innerHTML='';q.options.forEach(a=>{const b=document.createElement('button');b.className='answer';b.textContent=a;b.onclick=()=>answer(String(a));$('#answers').appendChild(b)})}
async function answer(a){if(game?.status!=='playing'||remaining()<=0)return finishStudent('time');const q=questions[idx],ok=String(a)===String(q.answer);$$('.answer').forEach(x=>x.disabled=true);$('#feedback').classList.remove('hidden');$('#feedback').classList.toggle('good',ok);$('#feedback').textContent=ok?'✨ ¡Correcto! +1 estrella':`💡 La respuesta correcta es: ${q.answer}`;if(ok)score++;responses.push({question:q,correct:ok,selected:String(a)});const evidence={challenge:q.challenge,standard:q.standard,content:q.content,subskill:q.subskill,skill:q.skill,layer:q.layer,cognitive:q.cognitive,difficulty:q.difficulty,correct:ok};try{await db.collection('games').doc(game.code).collection('players').doc(studentId).update({score,answered:idx+1,lastSkill:q.skill,lastStandard:q.standard,lastLayer:q.layer,evidence:firebase.firestore.FieldValue.arrayUnion(evidence)})}catch(e){console.error(e)}setTimeout(async()=>{idx++;$('#feedback').classList.add('hidden');if(idx>=questions.length)await finishStudent('completed');else if(game?.status==='playing')renderQ()},850)}
async function finishStudent(reason='completed'){if(finalizing)return;finalizing=true;stopTimer();const unanswered=Math.max(0,questions.length-responses.length),diagnostic=engine.diagnose(responses);show('finish');$('#finalScore').textContent=`⭐ ${score} / ${questions.length}`;$('#finalText').textContent=reason==='time'?`⏱️ Tiempo terminado. ${unanswered} desafío(s) quedaron sin responder.`:reason==='teacher'?`La partida fue terminada por el maestro. ${unanswered} desafío(s) quedaron sin responder.`:score===questions.length?'¡Misión perfecta! Excelente trabajo.':'¡Misión completada! Cada desafío te hace avanzar.';try{await db.collection('games').doc(game.code).collection('players').doc(studentId).update({score,answered:responses.length,unanswered,finished:true,finishReason:reason,finishedAt:firebase.firestore.FieldValue.serverTimestamp(),diagnostic});localStorage.removeItem('mathLiveActiveGame')}catch(e){console.error(e)}}
renderAvatars();try{initFirebase();ensureStudentAuth().catch(console.error)}catch(e){$('#joinMsg').innerHTML='<div class="status">Firebase no está disponible.</div>'}
