/* Math Live Student V6.0 K1 · © 2026 Rene M. Velazquez Avila */
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const sections=['studentJoin','studentWait','play','finish'];
function show(id){sections.forEach(x=>$('#'+x)?.classList.toggle('hidden',x!==id));window.scrollTo({top:0,behavior:'smooth'})}
const avatars=Array.from({length:18},(_,i)=>({id:`avatar-${String(i+1).padStart(2,'0')}`,src:`assets/avatar-${String(i+1).padStart(2,'0')}.webp?v=583`}));
function avatarSrc(id){return (avatars.find(a=>a.id===id)||avatars[0]).src}
function avatarImg(id,cls='avatarImage'){return `<img class="${cls}" src="${avatarSrc(id)}" alt="Avatar" draggable="false">`}
let selectedAvatar='avatar-01',db=null,auth=null,game=null,studentId=null,questions=[],idx=0,score=0,responses=[],unsubs=[],timerHandle=null,finalizing=false,audioPlays=0,audioCtx=null;
const engine=window.MathLiveEngineV2;

function visualHTML(q){
 const r=q.representation;if(!r)return'';
 const obj=(kind,i)=>kind==='star'?'★':kind==='apple'?'🍎':'●';
 const objects=(n,kind,layout)=>`<div class="visualObjects ${layout||'row'}">${Array.from({length:n},(_,i)=>`<button class="countObj" type="button" aria-label="objeto ${i+1}">${obj(kind,i)}</button>`).join('')}</div>`;
 const staticObjects=(n,kind,layout)=>`<div class="visualObjects ${layout||'row'}">${Array.from({length:n},(_,i)=>`<span class="countObj staticObj" aria-hidden="true">${obj(kind,i)}</span>`).join('')}</div>`;
 const frame=n=>`<div class="tenFrame">${Array.from({length:10},(_,i)=>`<span class="frameCell ${i<n?'filled':''}"></span>`).join('')}</div>`;
 if(r.type==='objectSet'||r.type==='touchCount')return objects(r.count,r.object,r.layout);
 if(r.type==='compareSets')return `<div class="compareVisual"><button type="button" class="visualChoice" data-answer="Izquierda" aria-label="Grupo izquierdo">${staticObjects(r.left,r.object,'fiveGroup')}</button><button type="button" class="visualChoice" data-answer="Derecha" aria-label="Grupo derecho">${staticObjects(r.right,r.object,'fiveGroup')}</button></div>`;
 if(r.type==='joinSets')return `<div class="joinVisual"><div>${objects(r.left,r.object,'fiveGroup')}</div><div class="joinSign">+</div><div>${objects(r.right,r.object,'fiveGroup')}</div></div>`;
 if(r.type==='numberPath'){let a=Math.max(0,r.center-2),nums=Array.from({length:5},(_,i)=>a+i);return `<div class="numberPath">${nums.map(n=>`<span class="${n===r.center?'focus':''}">${n}</span>`).join('')}</div>`}
 if(r.type==='equivalentGroups')return `<div class="frameVisual"><div>${frame(Math.min(10,r.a))}</div><div class="joinSign">+</div><div>${frame(Math.min(10,r.b))}</div></div>`;
 if(r.type==='tenFrameAdd')return `<div class="frameVisual"><div>${frame(Math.min(10,r.a))}${r.a>10?frame(r.a-10):''}</div><div class="joinSign">+</div><div>${frame(Math.min(10,r.b))}</div></div>`;
 if(r.type==='tenFrameMissing')return `<div class="frameVisual"><div><small>AHORA</small>${frame(Math.min(10,r.shown))}${r.shown>10?frame(r.shown-10):''}</div><div class="arrowBig">→</div><div><small>META ${r.target}</small>${frame(Math.min(10,r.target))}${r.target>10?frame(r.target-10):''}</div></div>`;
 if(r.type==='baseTenCompare'){const blocks=n=>`<div class="baseTen"><div class="tens">${'▮'.repeat(Math.floor(n/10))}</div><div class="ones">${'●'.repeat(n%10)}</div><strong>${n}</strong></div>`;return `<div class="compareVisual"><button type="button" class="visualChoice" data-answer="Izquierda" aria-label="Número izquierdo">${blocks(r.left)}</button><button type="button" class="visualChoice" data-answer="Derecha" aria-label="Número derecho">${blocks(r.right)}</button></div>`}
 if(r.type==='barGraph'){let max=Math.max(...r.values,1);return `<div class="barGraph">${r.values.map((v,i)=>`<div class="barCol"><div class="bar" style="height:${40+v/max*120}px"><span>${v}</span></div><strong>${r.labels[i]}</strong></div>`).join('')}</div>`}
 if(r.type==='ruler'){let ticks=Array.from({length:r.max+1},(_,i)=>`<span class="rTick ${i===r.end?'target':''}"><i></i><b>${i%5===0?i:''}</b></span>`).join('');return `<div class="rulerVisual"><div class="measureObj" style="width:${Math.max(12,r.end/r.max*100)}%"></div><div class="rulerTicks">${ticks}</div><small>cm</small></div>`}
 if(r.type==='compareRulers'){return `<div class="compareRulers"><div><div class="measureBar" style="width:${r.a/r.max*100}%"></div><b>${r.a} cm</b></div><div><div class="measureBar" style="width:${r.b/r.max*100}%"></div><b>${r.b} cm</b></div></div>`}
 if(r.type==='placeValueChart'||r.type==='regroupChart'){let col=(label,n,key)=>`<div class="pvCol ${r.focus===key?'focus':''}"><strong>${label}</strong><div class="pvDots">${Array.from({length:n},()=>'<i></i>').join('')}</div><b>${n}</b></div>`;return `<div class="pvChart">${col('100',r.hundreds,'hundreds')}${col('10',r.tens,'tens')}${col('1',r.ones,'ones')}</div>${r.action?`<div class="tradeHint">↔ ${r.action}</div>`:''}`}
 if(r.type==='placeValueCount'){return `<div class="pvCount"><strong>${r.start}</strong><span>→</span><div class="jumpBubble">+${r.step}</div><span>→</span><strong>?</strong></div>`}
 if(r.type==='comparePlaceValue'){let mk=n=>`<div class="pvMini"><b>${n}</b><span>${Math.floor(n/100)}C · ${Math.floor(n/10)%10}D · ${n%10}U</span></div>`;return `<div class="compareVisual">${mk(r.left)}<div class="compareQ">?</div>${mk(r.right)}</div>`}
 if(r.type==='moneyPV'){return `<div class="moneyPV"><div>${Array.from({length:r.hundreds},()=>'<span class="bill">$100</span>').join('')}</div><div>${Array.from({length:r.tens},()=>'<span class="bill ten">$10</span>').join('')}</div><div>${Array.from({length:r.ones},()=>'<span class="bill one">$1</span>').join('')}</div></div>`}
 if(r.type==='verticalRound'){let span=Math.max(1,r.high-r.low),pct=(r.number-r.low)/span*100;return `<div class="vRound"><b>${r.high}</b><div class="vLine"><span class="vPoint" style="bottom:${pct}%">${r.number}</span></div><b>${r.low}</b></div>`}
 if(r.type==='plotForms'){return `<div class="plotForms"><div><b>${r.start}</b><small>${r.startForm}</small></div><span>──────▶</span><div><b>?</b><small>${r.endForm}</small></div></div>`}
 if(r.type==='looseCollection'){return `<div class="looseCollection">${Array.from({length:r.count},()=>'<span>●</span>').join('')}</div>`}
 if(r.type==='equalGroups'||r.type==='storyGroups'||r.type==='twoStepGroups'){let groups=r.groups,each=r.each;return `<div class="equalGroups">${Array.from({length:groups},(_,gi)=>`<div class="groupBox">${Array.from({length:each},()=>'<i></i>').join('')}</div>`).join('')}</div>${r.remove?`<div class="removeTag">− ${r.remove}</div>`:''}`}
 if(r.type==='arrayModel'||r.type==='missingFactorArray'){let rows=r.rows||r.groups,cols=r.cols||Math.round(r.total/r.groups);return `<div class="arrayModel" style="--cols:${cols}">${Array.from({length:rows*cols},()=>'<i></i>').join('')}</div>`}
 if(r.type==='commutativeArrays'){let arr=(rows,cols)=>`<div class="arrayModel mini" style="--cols:${cols}">${Array.from({length:rows*cols},()=>'<i></i>').join('')}</div>`;return `<div class="commuteVisual">${arr(r.rows,r.cols)}<span>↔</span>${arr(r.cols,r.rows)}</div>`}
 if(r.type==='splitArray'){return `<div class="splitArray" style="--cols:${r.cols}">${Array.from({length:r.rows*r.cols},(_,i)=>`<i class="${i%r.cols>=r.cols-r.cut?'partB':''}"></i>`).join('')}</div>`}
 if(r.type==='divisionShare'||r.type==='divisionGrouping'){let total=r.total,groups=r.groups||Math.ceil(total/r.each);return `<div class="divisionVisual"><div class="pool">${Array.from({length:total},()=>'<i></i>').join('')}</div><span>→</span><div class="emptyGroups">${Array.from({length:groups},()=>'<b></b>').join('')}</div></div>`}
 if(r.type==='numberLineJumps'||r.type==='numberLineArc'){let start=r.start,end=r.end,lo=r.min??Math.min(start,end),hi=r.max??Math.max(start,end);let delta=end-start;return `<svg class="numberLineSvg" viewBox="0 0 720 190" role="img" aria-label="Recta numérica de ${start} a ${end}"><line x1="70" y1="135" x2="650" y2="135" stroke="currentColor" stroke-width="5"/><line x1="150" y1="120" x2="150" y2="150" stroke="currentColor" stroke-width="4"/><line x1="570" y1="120" x2="570" y2="150" stroke="currentColor" stroke-width="4"/><text x="150" y="175" text-anchor="middle">${start}</text><text x="570" y="175" text-anchor="middle">${end}</text><path d="M150 112 Q360 18 570 112" fill="none" stroke="currentColor" stroke-width="7" stroke-linecap="round"/><polygon points="570,112 545,102 550,126" fill="currentColor"/><text x="360" y="48" text-anchor="middle" class="jumpLabel">+${Math.abs(delta)}</text></svg>`}
 return'';
}
function speakText(text,lang,rate=.78){if(!('speechSynthesis'in window)||!text)return;try{const u=new SpeechSynthesisUtterance(text);u.lang=lang;u.rate=rate;const vs=speechSynthesis.getVoices();u.voice=vs.find(v=>v.lang?.toLowerCase().startsWith(lang.slice(0,2).toLowerCase()))||null;speechSynthesis.speak(u)}catch(e){}}
function speakQuestion(q,which=null){if(!('speechSynthesis'in window))return;try{speechSynthesis.cancel();audioPlays++;const pref=which||game?.language||'bilingual',rate=q.grade<=1?.76:.88;if(pref==='en')speakText(q.audioPromptEn||q.promptEn||q.audioPrompt||q.prompt,'en-US',rate);else if(pref==='es')speakText(q.audioPrompt||q.prompt,'es-US',rate);else{speechSynthesis.cancel();speakText(q.audioPrompt||q.prompt,'es-US',rate);setTimeout(()=>speakText(q.audioPromptEn||q.promptEn||q.audioPrompt||q.prompt,'en-US',rate),Math.max(900,(q.audioPrompt||q.prompt).length*48))}}catch(e){}}
function tone(freq=660,dur=.11,gain=.035){try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(gain,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur)}catch(e){}}
function soundStart(){tone(523,.08);setTimeout(()=>tone(659,.08),85);setTimeout(()=>tone(784,.13),170)}function soundGood(){tone(784,.08);setTimeout(()=>tone(988,.10),80)}function soundEnd(){tone(659,.10);setTimeout(()=>tone(784,.14),95)}
function promptHTML(q){const lang=game?.language||'bilingual',es=q.prompt,en=q.promptEn||q.prompt;if(lang==='en')return `<div class="promptText">${en}</div>`;if(lang==='es')return `<div class="promptText">${es}</div>`;return `<div class="promptText"><span class="langLine">🇪🇸 ${es}</span><span class="langLine en">🇺🇸 ${en}</span></div>`}
function optionLabel(a){if((game?.language||'bilingual')==='es')return a;const m={Izquierda:'Left',Derecha:'Right','Tienen igual':'They are equal','Son iguales':'They are equal'};return m[a]||a}

function bindVisualTouches(){document.querySelectorAll('.countObj').forEach(el=>el.onclick=e=>{e.stopPropagation();el.classList.toggle('touched')});document.querySelectorAll('.visualChoice').forEach(el=>el.onclick=()=>answer(String(el.dataset.answer)))}

function renderAvatars(){const el=$('#avatarGrid');el.innerHTML=avatars.map(a=>`<button type="button" class="avatar ${a.id===selectedAvatar?'active':''}" data-avatar="${a.id}" aria-label="Elegir avatar"><span class="avatarFace">${avatarImg(a.id)}</span></button>`).join('');$$('.avatar').forEach(b=>b.onclick=()=>{selectedAvatar=b.dataset.avatar;renderAvatars()})}
function initFirebase(){const c=window.MATHLIVE_FIREBASE_CONFIG||{};if(!window.firebase||!c.apiKey)throw Error('Firebase no está configurado.');if(!firebase.apps.length)firebase.initializeApp(c);db=firebase.firestore();auth=firebase.auth()}
async function ensureStudentAuth(){if(auth.currentUser){if(!auth.currentUser.isAnonymous)await auth.signOut();else return auth.currentUser}const c=await auth.signInAnonymously();return c.user}
function cleanup(){unsubs.forEach(f=>{try{f()}catch{}});unsubs=[];stopTimer()}
function stopTimer(){if(timerHandle){clearInterval(timerHandle);timerHandle=null}}
function fmt(sec){sec=Math.max(0,Math.ceil(sec));return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function startedMillis(){const t=game?.startedAt;return t&&typeof t.toMillis==='function'?t.toMillis():null}
function remaining(){const st=startedMillis();if(!st)return Number(game?.durationSeconds||900);return Math.max(0,Number(game?.durationSeconds||900)-(Date.now()-st)/1000)}
function runTimer(){stopTimer();const tick=async()=>{const left=remaining();$('#studentTimer').textContent=fmt(left);if(left<=0){stopTimer();await finishStudent('time')}};tick();timerHandle=setInterval(tick,500)}
function listenStudent(code){cleanup();unsubs.push(db.collection('games').doc(code).onSnapshot(s=>{if(!s.exists)return;game={code,...s.data()};if(game.status==='playing'&&$('#play').classList.contains('hidden'))startPlay();if(game.status==='finished'&&!finalizing)finishStudent(game.endedReason==='time'?'time':'teacher');if(game.status==='cancelled'){cleanup();show('studentJoin');$('#joinMsg').innerHTML='<div class="status">El maestro está modificando la partida. Espera el nuevo código.</div>'}},console.error))}
$('#joinGame').onclick=async()=>{try{let code=$('#joinCode').value.trim(),name=$('#studentName').value.trim().replace(/\s+/g,' ');if(!/^\d{6}$/.test(code)||!name){$('#joinMsg').innerHTML='<div class="status">Escribe un código válido de 6 dígitos y tu nombre.</div>';return}const user=await ensureStudentAuth(),ref=db.collection('games').doc(code),snap=await ref.get();if(!snap.exists){$('#joinMsg').innerHTML='<div class="status">Código no encontrado. Revisa los seis dígitos.</div>';return}game={code,...snap.data()};if(game.status!=='lobby'){$('#joinMsg').innerHTML='<div class="status">🔒 La partida ya comenzó. Ya no es posible unirse.</div>';return}studentId=user.uid;await ref.collection('players').doc(studentId).set({uid:user.uid,name,avatar:selectedAvatar,score:0,answered:0,finished:false,joinedAt:firebase.firestore.FieldValue.serverTimestamp()});$('#waitAvatar').innerHTML=avatarImg(selectedAvatar,'waitAvatarImg');$('#waitText').textContent=`${name}, ya estás conectado. Espera a que comience la aventura.`;localStorage.setItem('mathLiveActiveGame',JSON.stringify({code,name,avatar:selectedAvatar,uid:user.uid}));show('studentWait');listenStudent(code)}catch(e){console.error(e);$('#joinMsg').innerHTML='<div class="status">No pudimos entrar. Revisa la conexión y vuelve a intentar.</div>'}};
function startPlay(){if(!engine)return alert('No se pudo cargar el motor matemático.');soundStart();const bp=Array.isArray(game?.blueprint)&&game.blueprint.length?game.blueprint:engine.createGameBlueprint(game?.grade||2,game?.count||15);questions=engine.createStudentSet(bp,studentId);idx=0;score=0;responses=[];$('#playGrade').textContent=game?.gradeName||'';show('play');renderQ();runTimer()}
function renderQ(){const q=questions[idx];audioPlays=0;const visual=visualHTML(q);if(q.representation&&!visual){console.error('Representación no renderizada',q.representation,q);questions[idx]=engine.createStudentSet([game.blueprint[idx]],studentId+'-regen-'+idx)[0];return renderQ();}$('#progress').textContent=`${idx+1} / ${questions.length}`;$('#score').textContent=score;$('#skillLabel').textContent=q.grade<=1?'🎯 Math Live':`${q.content} · ${q.subskill} · ${q.layer}`;$('#question').style.whiteSpace='normal';const lang=game?.language||'bilingual',buttons=lang==='bilingual'?`<div class="audioBtns"><button id="hearES" class="hearQ" type="button" aria-label="Escuchar en español">🔊 ES</button><button id="hearEN" class="hearQ" type="button" aria-label="Listen in English">🔊 EN</button></div>`:`<button id="hearQ" class="hearQ" type="button" aria-label="Listen">🔊</button>`;$('#question').innerHTML=`${buttons}${promptHTML(q)}${visual}`;if(lang==='bilingual'){$('#hearES').onclick=()=>speakQuestion(q,'es');$('#hearEN').onclick=()=>speakQuestion(q,'en')}else $('#hearQ').onclick=()=>speakQuestion(q,lang);bindVisualTouches();$('#answers').innerHTML='';q.options.forEach(a=>{const b=document.createElement('button');b.className='answer';b.textContent=optionLabel(a);b.onclick=()=>answer(String(a));$('#answers').appendChild(b)});if(q.grade<=1)setTimeout(()=>speakQuestion(q,lang),300)}
async function answer(a){if(game?.status!=='playing'||remaining()<=0)return finishStudent('time');const q=questions[idx],ok=String(a)===String(q.answer);$$('.answer').forEach(x=>x.disabled=true);$('#feedback').classList.remove('hidden');$('#feedback').classList.toggle('good',ok);if(ok){soundGood();$('#feedback').textContent=(game?.language==='en'?'✨ Correct! +1 star':game?.language==='bilingual'?'✨ ¡Correcto! · Correct! +1 ⭐':'✨ ¡Correcto! +1 estrella')}else $('#feedback').textContent=game?.language==='en'?`💡 Correct answer: ${optionLabel(q.answer)}`:game?.language==='bilingual'?`💡 Respuesta correcta · Correct answer: ${optionLabel(q.answer)}`:`💡 La respuesta correcta es: ${q.answer}`;if(ok)score++;responses.push({question:q,correct:ok,selected:String(a)});const evidence={challenge:q.challenge,standard:q.standard,content:q.content,subskill:q.subskill,skill:q.skill,layer:q.layer,cognitive:q.cognitive,difficulty:q.difficulty,correct:ok,audioPlays,language:game?.language||'bilingual',representation:q.representation?.type||null};try{await db.collection('games').doc(game.code).collection('players').doc(studentId).update({score,answered:idx+1,lastSkill:q.skill,lastStandard:q.standard,lastLayer:q.layer,evidence:firebase.firestore.FieldValue.arrayUnion(evidence)})}catch(e){console.error(e)}setTimeout(async()=>{idx++;$('#feedback').classList.add('hidden');if(idx>=questions.length)await finishStudent('completed');else if(game?.status==='playing')renderQ()},850)}
async function finishStudent(reason='completed'){if(finalizing)return;finalizing=true;soundEnd();stopTimer();const unanswered=Math.max(0,questions.length-responses.length),diagnostic=engine.diagnose(responses);show('finish');$('#finalScore').textContent=`⭐ ${score} correctas de ${questions.length} · ${responses.length}/${questions.length} respondidas`;$('#finalText').textContent=reason==='time'?`⏱️ Tiempo terminado. ${unanswered} desafío(s) quedaron sin responder.`:reason==='teacher'?`La partida fue terminada por el maestro. ${unanswered} desafío(s) quedaron sin responder.`:responses.length===questions.length?(score===questions.length?'¡Misión perfecta! Excelente trabajo.':'¡Completaste los '+questions.length+' desafíos! Revisa tu resultado con el maestro.'):`Partida finalizada. ${unanswered} desafío(s) quedaron sin responder.`;try{await db.collection('games').doc(game.code).collection('players').doc(studentId).update({score,answered:responses.length,unanswered,finished:true,finishReason:reason,finishedAt:firebase.firestore.FieldValue.serverTimestamp(),diagnostic});localStorage.removeItem('mathLiveActiveGame')}catch(e){console.error(e)}}
renderAvatars();try{initFirebase();ensureStudentAuth().catch(console.error)}catch(e){$('#joinMsg').innerHTML='<div class="status">Firebase no está disponible.</div>'}
