/* Math Live Teacher V5.8.1 · © 2026 Rene M. Velazquez Avila */
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),engine=window.MathLiveEngineV2,modeRegistry=window.MathLiveModes;
const curriculum={K:{name:'Kinder',tag:'Cuenta y descubre'},1:{name:'1.º grado',tag:'Mira · cuenta · piensa'},2:{name:'2.º grado',tag:'Construye números'},3:{name:'3.º grado',tag:'Millares y operaciones'},4:{name:'4.º grado',tag:'Explora relaciones'},5:{name:'5.º grado',tag:'Retos avanzados'}};
const gameTypes=(modeRegistry?modeRegistry.list():[]).map(m=>[m.id,m.icon,m.name,m.short,m.enabled?'ready':'next']);
const avatarSrc=id=>`assets/${/^avatar-\d{2}$/.test(id||'')?id:'avatar-01'}.webp?v=583`;
const effectiveUnanswered=p=>Math.max(0,Number(game?.count||15)-Number(p.answered||0));
let db,auth,selectedGrade='2',selectedGame='integrated',game=null,unsubs=[],timerHandle=null,teacherPlayers=[];
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function show(id){['teacherLogin','teacherSetup','teacherLobby'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id));scrollTo({top:0,behavior:'smooth'})}
function initFirebase(){const c=window.MATHLIVE_FIREBASE_CONFIG||{};if(!window.firebase||!c.apiKey)throw Error('Firebase no está configurado.');if(!firebase.apps.length)firebase.initializeApp(c);db=firebase.firestore();auth=firebase.auth()}
function isRealTeacher(u){return !!u&&!u.isAnonymous}
function renderGrades(){$('#grades').innerHTML=['K','1','2','3','4','5'].map(k=>`<button class="grade ${k===selectedGrade?'active':''}" data-g="${k}"><strong>${k}</strong>${curriculum[k].name}<small>${curriculum[k].tag}</small></button>`).join('');$$('.grade').forEach(b=>b.onclick=()=>{selectedGrade=b.dataset.g;renderGrades();summary()})}
function renderGames(){$('#games').innerHTML=gameTypes.map(g=>{const ready=g[4]==='ready';return `<button class="game ${g[0]===selectedGame?'active':''}" data-game="${g[0]}" ${ready?'':'disabled'}>${g[1]}<b>${g[2]}</b><span class="modeNote">${ready?g[3]:'Próxima fase'}</span></button>`}).join('');$$('.game:not(:disabled)').forEach(b=>b.onclick=()=>{selectedGame=b.dataset.game;renderGames();summary()})}
function durationSeconds(){return Number($('#duration').value||900)}
function summary(){const gt=gameTypes.find(x=>x[0]===selectedGame)||['','🌟','Integrado'];$('#setupSummary').innerHTML=`<strong>${curriculum[selectedGrade].name}</strong> · ${gt[1]} ${gt[2]} · ${$('#qcount').value} desafíos · ${Math.round(durationSeconds()/60)} min<br><span class="small">CORE + REVIEW + APPLICATION · preguntas equivalentes y diferentes por estudiante</span>`}
function cleanup(){unsubs.forEach(f=>{try{f()}catch{}});unsubs=[];stopTimer()}
function stopTimer(){if(timerHandle){clearInterval(timerHandle);timerHandle=null}}
function fmt(sec){sec=Math.max(0,Math.ceil(sec));return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function remaining(){const t=game?.startedAt,st=t&&typeof t.toMillis==='function'?t.toMillis():null;if(!st)return Number(game?.durationSeconds||900);return Math.max(0,Number(game?.durationSeconds||900)-(Date.now()-st)/1000)}
function runTimer(){stopTimer();const tick=async()=>{const left=remaining();$('#teacherTimer').textContent=fmt(left);if(left<=0&&game?.status==='playing'){stopTimer();try{await db.collection('games').doc(game.code).update({status:'finished',endedReason:'time',endedAt:firebase.firestore.FieldValue.serverTimestamp()})}catch(e){console.error(e)}}};tick();timerHandle=setInterval(tick,500)}
async function uniqueCode(){for(let i=0;i<8;i++){const c=String(Math.floor(100000+Math.random()*900000)),s=await db.collection('games').doc(c).get();if(!s.exists)return c}throw Error('No se pudo generar código')}
$('#teacherLoginBtn').onclick=async()=>{const email=$('#teacherEmail').value.trim(),password=$('#teacherPassword').value;$('#loginMsg').innerHTML='';if(!email||!password){$('#loginMsg').innerHTML='<div class="status">Escribe tu correo y contraseña.</div>';return}try{const cred=await auth.signInWithEmailAndPassword(email,password);if(!isRealTeacher(cred.user))throw Error('Cuenta no válida');show('teacherSetup')}catch(e){console.error(e);$('#loginMsg').innerHTML='<div class="status">No se pudo iniciar sesión. Verifica la cuenta del maestro y que Email/Password esté habilitado en Firebase Authentication.</div>'}};
$('#teacherLogout').onclick=async()=>{cleanup();await auth.signOut();game=null;show('teacherLogin')};
$('#createGame').onclick=async()=>{try{const user=auth.currentUser;if(!isRealTeacher(user))throw Error('Acceso de maestro requerido');const newCode=await uniqueCode(),count=Number($('#qcount').value),gt=gameTypes.find(x=>x[0]===selectedGame),blueprint=engine.createGameBlueprint(selectedGrade,count);game={code:newCode,teacherUid:user.uid,grade:selectedGrade,gradeName:curriculum[selectedGrade].name,topic:'integrated',topicName:gt[2],gameType:selectedGame,gameName:gt[2],count,durationSeconds:durationSeconds(),mode:$('#mode').value,engineVersion:engine.VERSION,blueprint,status:'lobby',createdAt:firebase.firestore.FieldValue.serverTimestamp()};await db.collection('games').doc(newCode).set(game);$('#gameCode').textContent=newCode;$('#gameSummary').textContent=`${game.gradeName} · ${gt[1]} ${gt[2]} · ${count} desafíos · ${Math.round(game.durationSeconds/60)} min`;$('#teacherTimer').textContent=fmt(game.durationSeconds);show('teacherLobby');listenTeacher(newCode)}catch(e){console.error(e);alert('No se pudo crear la partida. Verifica el acceso del maestro y las reglas de Firestore.')}};
function listenTeacher(c){cleanup();unsubs.push(db.collection('games').doc(c).onSnapshot(s=>{if(!s.exists)return;game={code:c,...s.data()};const playing=game.status==='playing';$('#startGame').classList.toggle('hidden',playing||game.status==='finished');$('#modifyGame').classList.toggle('hidden',playing||game.status==='finished');$('#endGame').classList.toggle('hidden',!playing);if(playing)runTimer();if(game.status==='finished'){stopTimer();$('#teacherTimer').textContent='00:00';$('#teacherMsg').textContent='Partida finalizada.'}renderTeacherResults()},console.error));unsubs.push(db.collection('games').doc(c).collection('players').orderBy('joinedAt').onSnapshot(s=>{teacherPlayers=s.docs.map(d=>({id:d.id,...d.data()}));$('#studentCount').textContent=teacherPlayers.length;$('#studentList').innerHTML=teacherPlayers.map(p=>`<div class="playerCard"><div class="miniAvatar"><img src="${avatarSrc(p.avatar)}" alt=""></div><div class="playerInfo"><b>${esc(p.name)}</b><div class="playerState">${game?.status==='playing'||game?.status==='finished'?`Respondidas ${Number(p.answered||0)}/${Number(game?.count||15)} · ✓ ${Number(p.score||0)} · ✗ ${Math.max(0,Number(p.answered||0)-Number(p.score||0))}${game?.status==='finished'?` · ○ ${effectiveUnanswered(p)}`:''}`:'Conectado ✓'}</div></div></div>`).join('');if(game?.status==='lobby')$('#teacherMsg').textContent=teacherPlayers.length?'¡Equipo listo! Puedes comenzar cuando quieras.':'Esperando estudiantes…';renderTeacherResults()},console.error))}
$('#modifyGame').onclick=async()=>{if(!game)return;const n=teacherPlayers.length;if(n&&!confirm(`Hay ${n} estudiante(s) conectado(s). Este código se cancelará. ¿Continuar?`))return;await db.collection('games').doc(game.code).update({status:'cancelled',cancelledAt:firebase.firestore.FieldValue.serverTimestamp()});cleanup();game=null;show('teacherSetup');summary()};
$('#openTV').onclick=()=>{if(!game?.code)return;const u=new URL('present.html',location.href);u.searchParams.set('code',game.code);window.open(u.toString(),'mathLiveTV')};
$('#startGame').onclick=async()=>{if(!game)return;await db.collection('games').doc(game.code).update({status:'playing',startedAt:firebase.firestore.FieldValue.serverTimestamp()})};
$('#endGame').onclick=async()=>{if(!game||game.status!=='playing'||!confirm('¿Terminar la partida ahora?'))return;await db.collection('games').doc(game.code).update({status:'finished',endedReason:'teacher',endedAt:firebase.firestore.FieldValue.serverTimestamp()})};
function finalOrder(list){return [...list].sort((a,b)=>Number(b.score||0)-Number(a.score||0)||((a.finishedAt?.toMillis?.()??Infinity)-(b.finishedAt?.toMillis?.()??Infinity))||String(a.name).localeCompare(String(b.name),'es'))}
function statusClass(x){return x==='Fortaleza'?'tagGood':x==='En desarrollo'?'tagDev':x==='Necesita apoyo'?'tagNeed':'tagLimited'}
function renderTeacherResults(){if(!game)return;const visible=game.status==='finished'||teacherPlayers.some(p=>p.finished);$('#teacherResults').classList.toggle('hidden',!visible);if(!visible)return;const total=teacherPlayers.length,finished=teacherPlayers.filter(p=>p.finished).length,possible=total*Number(game.count||15),correct=teacherPlayers.reduce((a,p)=>a+Number(p.score||0),0),unanswered=teacherPlayers.reduce((a,p)=>a+effectiveUnanswered(p),0),pct=possible?Math.round(correct/possible*100):0;$('#classSummary').innerHTML=`<div class="reportStats"><div class="reportStat"><b>${total}</b>estudiantes</div><div class="reportStat"><b>${finished}</b>finalizaron</div><div class="reportStat"><b>${pct}%</b>aciertos del total</div><div class="reportStat"><b>${unanswered}</b>sin responder</div></div>`;let rows=[];teacherPlayers.forEach(p=>{const ds=Array.isArray(p.diagnostic)?p.diagnostic:[];if(!ds.length)rows.push(`<tr><td><b>${esc(p.name)}</b></td><td colspan="5">Sin evidencia diagnóstica suficiente todavía.</td></tr>`);else ds.forEach(d=>rows.push(`<tr><td><b>${esc(p.name)}</b></td><td>${esc(d.standard||'—')}</td><td>${esc(d.content||'—')}</td><td>${esc(d.subskill||'—')}</td><td>${Number(d.correct||0)}/${Number(d.total||0)} (${Number(d.rate||0)}%)</td><td><span class="${statusClass(d.status)}">${esc(d.status)}</span></td></tr>`))});$('#diagnosticTable').innerHTML=`<div class="diagWrap"><table class="diagTable"><thead><tr><th>Estudiante</th><th>Estándar</th><th>Contenido</th><th>Subhabilidad</th><th>Evidencia</th><th>Estado</th></tr></thead><tbody>${rows.join('')}</tbody></table></div>`}
function csvCell(v){return '"'+String(v??'').replace(/"/g,'""')+'"'}
$('#downloadReport').onclick=()=>{const lines=[['Math Live - Reporte diagnóstico'],['Código',game?.code],['Grado',game?.gradeName],['Modo',game?.gameName],[],['Estudiante','Aciertos','Respondidas','Sin responder','Estándar','Contenido','Subhabilidad','Evidencia','Estado']];teacherPlayers.forEach(p=>{const ds=Array.isArray(p.diagnostic)?p.diagnostic:[];if(ds.length)ds.forEach(d=>lines.push([p.name,p.score||0,p.answered||0,effectiveUnanswered(p),d.standard,d.content,d.subskill,`${d.correct}/${d.total} (${d.rate}%)`,d.status]));else lines.push([p.name,p.score||0,p.answered||0,effectiveUnanswered(p),'','','','','Sin evidencia'])});const blob=new Blob(['\ufeff'+lines.map(r=>r.map(csvCell).join(',')).join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Math_Live_${game?.code||'reporte'}_diagnostico.csv`;a.click()};
$('#printCertificates').onclick=()=>{const top=finalOrder(teacherPlayers).slice(0,3);if(!top.length)return alert('Todavía no hay resultados.');const w=open('','_blank');w.document.write(`<!doctype html><meta charset="utf-8"><title>Math Live · Top 3</title><style>@page{size:letter landscape;margin:.35in}body{font-family:Arial;color:#35286d}.cert{height:7.3in;border:10px double #6b50c5;border-radius:24px;padding:.35in;text-align:center;page-break-after:always;position:relative}.cert h1{font-size:38px}.cert h2{font-size:44px}.sign{position:absolute;bottom:.45in;left:0;right:0}.line{width:240px;border-top:1px solid #555;margin:0 auto 8px}</style>${top.map((p,i)=>`<section class="cert"><div style="font-size:58px">${['🥇','🥈','🥉'][i]}</div><b>MATH LIVE</b><h1>Certificate of Achievement</h1><p>This certificate recognizes</p><h2>${esc(p.name)}</h2><p>for outstanding performance in Math Live</p><h3>${i+1}.º lugar · ${Number(p.score||0)}/${Number(game?.count||15)} correctas</h3><div class="sign"><div class="line"></div><b>Rene Velazquez</b><br>Second Grade Teacher</div></section>`).join('')}<script>setTimeout(()=>print(),350)<\/script>`);w.document.close()};
renderGrades();renderGames();summary();$('#qcount').onchange=summary;$('#duration').onchange=summary;
try{initFirebase();auth.onAuthStateChanged(u=>{if(isRealTeacher(u))show('teacherSetup');else show('teacherLogin')})}catch(e){$('#loginMsg').innerHTML='<div class="status">Firebase no está disponible.</div>'}
