/* Math Live Teacher V5.8.6 · © 2026 Rene M. Velazquez Avila */
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),engine=window.MathLiveEngineV2,modeRegistry=window.MathLiveModes;
const curriculum={K:{name:'Kinder',tag:'Cuenta y descubre'},1:{name:'1.º grado',tag:'Mira · cuenta · piensa'},2:{name:'2.º grado',tag:'Construye números'},3:{name:'3.º grado',tag:'Millares y operaciones'},4:{name:'4.º grado',tag:'Explora relaciones'},5:{name:'5.º grado',tag:'Retos avanzados'}};
const gameTypes=(modeRegistry?modeRegistry.list():[]).map(m=>[m.id,m.icon,m.name,m.short,m.enabled?'ready':'next']);
const avatarSrc=id=>`assets/${/^avatar-\d{2}$/.test(id||'')?id:'avatar-01'}.webp?v=585`;
const effectiveUnanswered=p=>Math.max(0,Number(game?.count||15)-Number(p.answered||0));
const engineGrade=k=>k==='K'?0:Number(k);
function validEngineGrade(k){const g=engineGrade(k);return Number.isInteger(g)&&g>=0&&g<=5}
let db,auth,selectedGrade='2',selectedGame='integrated',game=null,unsubs=[],timerHandle=null,teacherPlayers=[],knownPlayerIds=new Set(),playersSnapshotReady=false;
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function show(id){['teacherLogin','teacherSetup','teacherHistory','teacherLobby'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id));scrollTo({top:0,behavior:'smooth'})}
function initFirebase(){const c=window.MATHLIVE_FIREBASE_CONFIG||{};if(!window.firebase||!c.apiKey)throw Error('Firebase no está configurado.');if(!firebase.apps.length)firebase.initializeApp(c);db=firebase.firestore();auth=firebase.auth()}
function isRealTeacher(u){return !!u&&!u.isAnonymous}
function renderGrades(){$('#grades').innerHTML=['K','1','2','3','4','5'].map(k=>`<button class="grade ${k===selectedGrade?'active':''}" data-g="${k}"><strong>${k}</strong>${curriculum[k].name}<small>${curriculum[k].tag}</small></button>`).join('');$$('.grade').forEach(b=>b.onclick=()=>{selectedGrade=b.dataset.g;renderGrades();summary()})}
function renderGames(){$('#games').innerHTML=gameTypes.map(g=>{const ready=g[4]==='ready';return `<button class="game ${g[0]===selectedGame?'active':''}" data-game="${g[0]}" ${ready?'':'disabled'}>${g[1]}<b>${g[2]}</b><span class="modeNote">${ready?g[3]:'Próxima fase'}</span></button>`}).join('');$$('.game:not(:disabled)').forEach(b=>b.onclick=()=>{selectedGame=b.dataset.game;renderGames();summary()})}
function durationSeconds(){return Number($('#duration').value||900)}
function summary(){const gt=gameTypes.find(x=>x[0]===selectedGame)||['','🌟','Integrado'],lang=$('#language')?.selectedOptions?.[0]?.textContent||'🌎 Bilingüe · ES / EN';$('#setupSummary').innerHTML=`<strong>${curriculum[selectedGrade].name}</strong> · ${gt[1]} ${gt[2]} · ${$('#qcount').value} desafíos · ${Math.round(durationSeconds()/60)} min · ${lang}<br><span class="small">CORE + REVIEW + APPLICATION · preguntas equivalentes y diferentes por estudiante</span>`}
function cleanup(){unsubs.forEach(f=>{try{f()}catch{}});unsubs=[];stopTimer()}
function stopTimer(){if(timerHandle){clearInterval(timerHandle);timerHandle=null}}
function fmt(sec){sec=Math.max(0,Math.ceil(sec));return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function remaining(){const t=game?.startedAt,st=t&&typeof t.toMillis==='function'?t.toMillis():null;if(!st)return Number(game?.durationSeconds||900);return Math.max(0,Number(game?.durationSeconds||900)-(Date.now()-st)/1000)}
function runTimer(){stopTimer();const tick=async()=>{const left=remaining();$('#teacherTimer').textContent=fmt(left);if(left<=0&&game?.status==='playing'){stopTimer();try{await db.collection('games').doc(game.code).update({status:'finished',endedReason:'time',endedAt:firebase.firestore.FieldValue.serverTimestamp()})}catch(e){console.error(e)}}};tick();timerHandle=setInterval(tick,500)}
async function uniqueCode(){for(let i=0;i<8;i++){const c=String(Math.floor(100000+Math.random()*900000)),s=await db.collection('games').doc(c).get();if(!s.exists)return c}throw Error('No se pudo generar código')}
$('#teacherLoginBtn').onclick=async()=>{const email=$('#teacherEmail').value.trim(),password=$('#teacherPassword').value;$('#loginMsg').innerHTML='';if(!email||!password){$('#loginMsg').innerHTML='<div class="status">Escribe tu correo y contraseña.</div>';return}try{const cred=await auth.signInWithEmailAndPassword(email,password);if(!isRealTeacher(cred.user))throw Error('Cuenta no válida');show('teacherSetup')}catch(e){console.error(e);$('#loginMsg').innerHTML='<div class="status">No se pudo iniciar sesión. Verifica la cuenta del maestro y que Email/Password esté habilitado en Firebase Authentication.</div>'}};
$('#teacherLogout').onclick=async()=>{cleanup();await auth.signOut();game=null;show('teacherLogin')};
let audioCtx=null;function tone(freq=740,dur=.11,gain=.045){try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(gain,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur)}catch(e){}}
function soundJoin(){tone(784,.10,.04);setTimeout(()=>tone(988,.12,.035),90)}
function soundStart(){tone(523,.08,.04);setTimeout(()=>tone(659,.08,.04),85);setTimeout(()=>tone(784,.14,.04),170)}
function soundEnd(){tone(784,.10,.035);setTimeout(()=>tone(659,.12,.035),100)}
$('#createGame').onclick=async()=>{try{const user=auth.currentUser;if(!isRealTeacher(user))throw Error('Acceso de maestro requerido');const newCode=await uniqueCode(),count=Number($('#qcount').value),gt=gameTypes.find(x=>x[0]===selectedGame),gradeForEngine=engineGrade(selectedGrade);if(!validEngineGrade(selectedGrade))throw Error(`Grado inválido: ${selectedGrade}`);const blueprint=engine.createGameBlueprint(gradeForEngine,count);game={code:newCode,teacherUid:user.uid,grade:gradeForEngine,gradeKey:selectedGrade,gradeName:curriculum[selectedGrade].name,topic:'integrated',topicName:gt[2],gameType:selectedGame,gameName:gt[2],count,durationSeconds:durationSeconds(),mode:$('#mode').value,language:$('#language')?.value||'bilingual',engineVersion:engine.VERSION,blueprint,status:'lobby',createdAt:firebase.firestore.FieldValue.serverTimestamp()};await db.collection('games').doc(newCode).set(game);$('#gameCode').textContent=newCode;$('#gameSummary').textContent=`${game.gradeName} · ${gt[1]} ${gt[2]} · ${count} desafíos · ${Math.round(game.durationSeconds/60)} min`;$('#teacherTimer').textContent=fmt(game.durationSeconds);show('teacherLobby');listenTeacher(newCode)}catch(e){console.error(e);const m=String(e?.message||e||'Error desconocido');alert(`No se pudo crear la partida.\n\nDetalle: ${m}`)}};
function listenTeacher(c){cleanup();unsubs.push(db.collection('games').doc(c).onSnapshot(s=>{if(!s.exists)return;game={code:c,...s.data()};const playing=game.status==='playing';$('#startGame').classList.toggle('hidden',playing||game.status==='finished');$('#modifyGame').classList.toggle('hidden',playing||game.status==='finished');$('#endGame').classList.toggle('hidden',!playing);if(playing)runTimer();if(game.status==='finished'){stopTimer();$('#teacherTimer').textContent='00:00';$('#teacherMsg').textContent='Partida finalizada.'}renderTeacherResults()},console.error));unsubs.push(db.collection('games').doc(c).collection('players').orderBy('joinedAt').onSnapshot(s=>{const currentIds=new Set(s.docs.map(d=>d.id));if(playersSnapshotReady){const added=s.docChanges().filter(ch=>ch.type==='added'&&!knownPlayerIds.has(ch.doc.id));if(added.length)added.forEach((_,i)=>setTimeout(soundJoin,i*120));}knownPlayerIds=currentIds;playersSnapshotReady=true;teacherPlayers=s.docs.map(d=>({id:d.id,...d.data()}));$('#studentCount').textContent=teacherPlayers.length;$('#studentList').innerHTML=teacherPlayers.map(p=>`<div class="playerCard"><div class="miniAvatar"><img src="${avatarSrc(p.avatar)}" alt=""></div><div class="playerInfo"><b>${esc(p.name)}</b><div class="playerState">${game?.status==='playing'||game?.status==='finished'?`Respondidas ${Number(p.answered||0)}/${Number(game?.count||15)} · ✓ ${Number(p.score||0)} · ✗ ${Math.max(0,Number(p.answered||0)-Number(p.score||0))}${game?.status==='finished'?` · ○ ${effectiveUnanswered(p)}`:''}`:'Conectado ✓'}</div></div></div>`).join('');if(game?.status==='lobby')$('#teacherMsg').textContent=teacherPlayers.length?'¡Equipo listo! Puedes comenzar cuando quieras.':'Esperando estudiantes…';renderTeacherResults()},console.error))}
$('#modifyGame').onclick=async()=>{if(!game)return;const n=teacherPlayers.length;if(n&&!confirm(`Hay ${n} estudiante(s) conectado(s). Este código se cancelará. ¿Continuar?`))return;await db.collection('games').doc(game.code).update({status:'cancelled',cancelledAt:firebase.firestore.FieldValue.serverTimestamp()});cleanup();game=null;show('teacherSetup');summary()};
$('#openTV').onclick=()=>{if(!game?.code)return;const u=new URL('present.html',location.href);u.searchParams.set('code',game.code);window.open(u.toString(),'mathLiveTV')};
$('#startGame').onclick=async()=>{soundStart();if(!game)return;await db.collection('games').doc(game.code).update({status:'playing',startedAt:firebase.firestore.FieldValue.serverTimestamp()})};
$('#endGame').onclick=async()=>{if(!game||game.status!=='playing'||!confirm('¿Terminar la partida ahora?'))return;soundEnd();await db.collection('games').doc(game.code).update({status:'finished',endedReason:'teacher',endedAt:firebase.firestore.FieldValue.serverTimestamp()})};
function finalOrder(list){return [...list].sort((a,b)=>Number(b.score||0)-Number(a.score||0)||((a.finishedAt?.toMillis?.()??Infinity)-(b.finishedAt?.toMillis?.()??Infinity))||String(a.name).localeCompare(String(b.name),'es'))}
function statusClass(x){return x==='Fortaleza'?'tagGood':x==='En desarrollo'?'tagDev':x==='Necesita apoyo'?'tagNeed':'tagLimited'}
function renderTeacherResults(){if(!game)return;const visible=game.status==='finished'||teacherPlayers.some(p=>p.finished);$('#teacherResults').classList.toggle('hidden',!visible);if(!visible)return;const total=teacherPlayers.length,finished=teacherPlayers.filter(p=>p.finished).length,possible=total*Number(game.count||15),correct=teacherPlayers.reduce((a,p)=>a+Number(p.score||0),0),unanswered=teacherPlayers.reduce((a,p)=>a+effectiveUnanswered(p),0),pct=possible?Math.round(correct/possible*100):0;$('#classSummary').innerHTML=`<div class="reportStats"><div class="reportStat"><b>${total}</b>estudiantes</div><div class="reportStat"><b>${finished}</b>finalizaron</div><div class="reportStat"><b>${pct}%</b>aciertos del total</div><div class="reportStat"><b>${unanswered}</b>sin responder</div></div>`;const ordered=finalOrder(teacherPlayers);$('#diagnosticTable').innerHTML=`<div class="studentResults">${ordered.map(p=>{const wrong=Math.max(0,Number(p.answered||0)-Number(p.score||0)),un=effectiveUnanswered(p),rate=Number(game.count||15)?Math.round(Number(p.score||0)/Number(game.count||15)*100):0;return `<div class="studentResult"><div class="srName"><img src="${avatarSrc(p.avatar)}" alt=""><div><b>${esc(p.name)}</b><div class="small">${p.finished?'Finalizó':'No completó la partida'}</div></div></div><div class="srMetric"><b>${Number(p.answered||0)}/${Number(game.count||15)}</b>respondidas</div><div class="srMetric"><b>${Number(p.score||0)}</b>correctas</div><div class="srMetric"><b>${wrong}</b>incorrectas</div><div class="srMetric"><b>${un}</b>sin responder</div><button class="btn ghost smallBtn detailBtn" data-id="${esc(p.id)}">VER DETALLES</button><div id="detail-${esc(p.id)}" class="detailBox hidden" style="grid-column:1/-1"></div></div>`}).join('')}</div>`;$$('.detailBtn').forEach(b=>b.onclick=()=>toggleStudentDetail(b.dataset.id))}
function toggleStudentDetail(id){const p=teacherPlayers.find(x=>x.id===id),box=$('#detail-'+CSS.escape(id));if(!p||!box)return;if(!box.classList.contains('hidden')){box.classList.add('hidden');return}const ds=Array.isArray(p.diagnostic)?p.diagnostic:[];box.innerHTML=`<div class="row" style="justify-content:space-between;align-items:center"><div><b>Diagnóstico de ${esc(p.name)}</b><div class="small">Aciertos ${Number(p.score||0)}/${Number(game.count||15)} · Respondidas ${Number(p.answered||0)} · Sin responder ${effectiveUnanswered(p)}</div></div><button class="btn smallBtn individualDownload" data-id="${esc(p.id)}">⬇️ DESCARGAR REPORTE INDIVIDUAL</button></div>${ds.length?`<div class="diagWrap"><table class="diagTable"><thead><tr><th>Estándar</th><th>Contenido</th><th>Subhabilidad</th><th>Evidencia</th><th>Estado</th></tr></thead><tbody>${ds.map(d=>`<tr><td>${esc(d.standard||'—')}</td><td>${esc(d.content||'—')}</td><td>${esc(d.subskill||'—')}</td><td>${Number(d.correct||0)}/${Number(d.total||0)} (${Number(d.rate||0)}%)</td><td><span class="${statusClass(d.status)}">${esc(d.status)}</span></td></tr>`).join('')}</tbody></table></div>`:'<p class="small">Sin evidencia diagnóstica suficiente.</p>'}`;box.classList.remove('hidden');box.querySelector('.individualDownload').onclick=()=>downloadIndividual(id)}
function downloadIndividual(id){const p=teacherPlayers.find(x=>x.id===id);if(!p)return;const rows=[['Math Live - Reporte individual'],['Estudiante',p.name],['Código',game.code],['Grado',game.gradeName],['Modo',game.gameName],['Correctas',p.score||0],['Respondidas',p.answered||0],['Sin responder',effectiveUnanswered(p)],[],['Estándar','Contenido','Subhabilidad','Evidencia','Estado']];(p.diagnostic||[]).forEach(d=>rows.push([d.standard,d.content,d.subskill,`${d.correct}/${d.total} (${d.rate}%)`,d.status]));downloadCsv(rows,`Math_Live_${safeName(p.name)}_${game.code}.csv`)}
function safeName(v){return String(v||'estudiante').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'_')}
function downloadCsv(rows,name){const blob=new Blob(['\ufeff'+rows.map(r=>r.map(csvCell).join(',')).join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function csvCell(v){return '"'+String(v??'').replace(/"/g,'""')+'"'}
$('#downloadReport').onclick=()=>{if(!window.XLSX)return alert('No se pudo cargar el generador de Excel. Revisa la conexión a Internet.');const wb=XLSX.utils.book_new();const total=teacherPlayers.length,possible=total*Number(game.count||15),correct=teacherPlayers.reduce((a,p)=>a+Number(p.score||0),0),unanswered=teacherPlayers.reduce((a,p)=>a+effectiveUnanswered(p),0);const summary=[['Math Live - Reporte general'],['Código',game.code],['Fecha',new Date().toLocaleString()],['Grado',game.gradeName],['Modalidad',game.gameName],['Desafíos',game.count],['Estudiantes',total],['Finalizaron',teacherPlayers.filter(p=>p.finished).length],['Aciertos del total',possible?Math.round(correct/possible*100)+'%':'0%'],['Sin responder',unanswered]];const students=[['Estudiante','Correctas','Respondidas','Incorrectas','Sin responder','Porcentaje','Finalizó']];finalOrder(teacherPlayers).forEach(p=>students.push([p.name,Number(p.score||0),Number(p.answered||0),Math.max(0,Number(p.answered||0)-Number(p.score||0)),effectiveUnanswered(p),Number(game.count||15)?Math.round(Number(p.score||0)/Number(game.count||15)*100)/100:0,p.finished?'Sí':'No']));const detail=[['Estudiante','Estándar','Contenido','Subhabilidad','Correctas','Total evidencia','Porcentaje','Estado']];teacherPlayers.forEach(p=>(p.diagnostic||[]).forEach(d=>detail.push([p.name,d.standard,d.content,d.subskill,Number(d.correct||0),Number(d.total||0),Number(d.rate||0)/100,d.status])));const skills={};teacherPlayers.forEach(p=>(p.diagnostic||[]).forEach(d=>{const k=[d.standard,d.content,d.subskill].join(' | ');skills[k]??={standard:d.standard,content:d.content,subskill:d.subskill,correct:0,total:0};skills[k].correct+=Number(d.correct||0);skills[k].total+=Number(d.total||0)}));const skillRows=[['Estándar','Contenido','Subhabilidad','Correctas','Evidencias','Porcentaje']];Object.values(skills).forEach(x=>skillRows.push([x.standard,x.content,x.subskill,x.correct,x.total,x.total?x.correct/x.total:0]));[['Resumen de clase',summary],['Estudiantes',students],['Resultados por habilidad',skillRows],['Datos detallados',detail]].forEach(([n,data])=>{const ws=XLSX.utils.aoa_to_sheet(data);ws['!cols']=data[0].map((_,i)=>({wch:Math.min(42,Math.max(12,...data.map(r=>String(r[i]??'').length+2)))}));XLSX.utils.book_append_sheet(wb,ws,n)});XLSX.writeFile(wb,`Math_Live_${game.code}_Reporte_General.xlsx`)};
$('#printCertificates').onclick=()=>{const top=finalOrder(teacherPlayers).slice(0,3);if(!top.length)return alert('Todavía no hay resultados.');const w=open('','_blank');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Math Live · Top 3</title><style>@page{size:letter landscape;margin:0}*{box-sizing:border-box}html,body{margin:0;padding:0;font-family:Arial,sans-serif;color:#35286d}.cert{width:11in;height:8.5in;padding:.42in .55in;position:relative;text-align:center;page-break-after:always;break-after:page;overflow:hidden}.cert:last-child{page-break-after:auto;break-after:auto}.frame{height:100%;border:8px double #6b50c5;border-radius:22px;padding:.28in;position:relative}.medal{font-size:48px;line-height:1}.brand{font-weight:900;letter-spacing:2px;margin:4px}.avatar{width:82px;height:82px;border-radius:50%;object-fit:cover;border:4px solid #eee8ff}.cert h1{font-size:30px;margin:7px}.cert h2{font-size:40px;margin:8px}.cert p{margin:7px}.result{font-size:19px;font-weight:900}.sign{position:absolute;bottom:.3in;left:0;right:0}.sign b{font-size:16px}.motto{margin-top:10px;font-weight:800;color:#6b50c5}</style></head><body>${top.map((p,i)=>`<section class="cert"><div class="frame"><div class="medal">${['🥇','🥈','🥉'][i]}</div><div class="brand">MATH LIVE</div><h1>Certificate of Achievement</h1><p>This certificate is proudly presented to</p><img class="avatar" src="${new URL(avatarSrc(p.avatar),location.href).href}"><h2>${esc(p.name)}</h2><p>for outstanding performance in Math Live</p><div class="result">${['1st','2nd','3rd'][i]} Place · ${Number(p.score||0)}/${Number(game?.count||15)} Correct</div><div class="motto">Juega · Aprende · Avanza</div><div class="sign"><b>Rene Velazquez</b><br><span>Second Grade Teacher</span></div></div></section>`).join('')}<script>window.onload=()=>setTimeout(()=>window.print(),300)<\/script></body></html>`);w.document.close()};
function resetForNewGame(){cleanup();game=null;teacherPlayers=[];knownPlayerIds=new Set();playersSnapshotReady=false;$('#studentList').innerHTML='';$('#teacherResults').classList.add('hidden');show('teacherSetup');summary()}
$('#newGameTop').onclick=resetForNewGame;$('#newGameAfter').onclick=resetForNewGame;$('#historyAfter').onclick=()=>loadHistory();$('#openHistory').onclick=()=>loadHistory();$('#historyBack').onclick=()=>show('teacherSetup');
async function loadHistory(){const u=auth.currentUser;if(!isRealTeacher(u))return;cleanup();show('teacherHistory');$('#historyMsg').textContent='Cargando partidas…';$('#historyList').innerHTML='';try{const snap=await db.collection('games').where('teacherUid','==',u.uid).get();const games=snap.docs.map(d=>({code:d.id,...d.data()})).filter(g=>g.status==='finished').sort((a,b)=>((b.endedAt?.toMillis?.()||b.createdAt?.toMillis?.()||0)-(a.endedAt?.toMillis?.()||a.createdAt?.toMillis?.()||0)));$('#historyMsg').textContent=games.length?`${games.length} partida(s) finalizada(s)`:'Todavía no hay partidas finalizadas.';$('#historyList').innerHTML=games.length?games.map(g=>{const dt=g.endedAt?.toDate?.()||g.createdAt?.toDate?.();return `<div class="historyCard"><div><b>${esc(g.gradeName||g.grade||'Partida')} · ${esc(g.gameName||'Integrado')}</b><div class="historyMeta">${dt?dt.toLocaleString():'Fecha no disponible'} · Código ${esc(g.code)}</div></div><div><b>${Number(g.count||15)}</b><div class="historyMeta">desafíos</div></div><div><b>${Math.round(Number(g.durationSeconds||900)/60)} min</b><div class="historyMeta">duración</div></div><button class="btn smallBtn historyOpen" data-code="${esc(g.code)}">VER RESULTADOS</button></div>`}).join(''):'<div class="historyEmpty">Las partidas que finalices aparecerán aquí.</div>';$$('.historyOpen').forEach(b=>b.onclick=()=>openHistoricalGame(b.dataset.code))}catch(e){console.error(e);$('#historyMsg').textContent='No se pudo cargar el historial.'}}
async function openHistoricalGame(code){try{const gs=await db.collection('games').doc(code).get();if(!gs.exists)return;game={code,...gs.data()};const ps=await db.collection('games').doc(code).collection('players').get();teacherPlayers=ps.docs.map(d=>({id:d.id,...d.data()}));$('#gameCode').textContent=code;$('#gameSummary').textContent=`${game.gradeName||game.grade} · ${game.gameName||'Integrado'} · ${Number(game.count||15)} desafíos · ${Math.round(Number(game.durationSeconds||900)/60)} min`;$('#studentCount').textContent=teacherPlayers.length;$('#teacherTimer').textContent='00:00';$('#studentList').innerHTML=teacherPlayers.map(p=>`<div class="playerCard"><div class="miniAvatar"><img src="${avatarSrc(p.avatar)}" alt=""></div><div class="playerInfo"><b>${esc(p.name)}</b><div class="playerState">Respondidas ${Number(p.answered||0)}/${Number(game.count||15)} · ✓ ${Number(p.score||0)} · ✗ ${Math.max(0,Number(p.answered||0)-Number(p.score||0))} · ○ ${effectiveUnanswered(p)}</div></div></div>`).join('');$('#teacherMsg').textContent='Partida finalizada · registro histórico.';show('teacherLobby');$('#startGame').classList.add('hidden');$('#modifyGame').classList.add('hidden');$('#endGame').classList.add('hidden');renderTeacherResults()}catch(e){console.error(e);alert('No se pudo abrir esta partida.')}}
renderGrades();renderGames();summary();$('#qcount').onchange=summary;$('#duration').onchange=summary;if($('#language'))$('#language').onchange=summary;
try{initFirebase();auth.onAuthStateChanged(u=>{if(isRealTeacher(u))show('teacherSetup');else show('teacherLogin')})}catch(e){$('#loginMsg').innerHTML='<div class="status">Firebase no está disponible.</div>'}
